// Regenerates data/countries-meta.js from the `world-countries` npm package.
//
//   npm pack world-countries && tar xzf world-countries-*.tgz
//   node tools/build-meta.mjs package/countries.json
//
// Only needed when updating the reference data; the site itself has no build step.
import { readFileSync, writeFileSync } from 'node:fs';

const [src = 'package/countries.json'] = process.argv.slice(2);
const countries = JSON.parse(readFileSync(src, 'utf8'));

// Holy See is a UN observer, not a member (the dataset marks it as a member).
const NOT_UN = new Set(['VAT']);

function continentOf(c) {
    if (c.region === 'Americas') return c.subregion === 'South America' ? 'South America' : 'North America';
    if (c.region === 'Antarctic') return 'Antarctica';
    return c.region;
}

const meta = {};
for (const c of [...countries].sort((a, b) => a.cca3.localeCompare(b.cca3))) {
    meta[c.cca3] = {
        name: c.name.common,
        continent: continentOf(c),
        subregion: c.subregion || '',
        un: c.unMember && !NOT_UN.has(c.cca3),
        num: c.ccn3 || null,
        lat: +c.latlng[0].toFixed(3),
        lng: +c.latlng[1].toFixed(3),
        area: c.area,
    };
}

const body = Object.entries(meta).map(([k, v]) => `    ${k}: ${JSON.stringify(v)},`).join('\n');
writeFileSync(new URL('../data/countries-meta.js', import.meta.url),
`// Reference data for every country/territory, keyed by ISO 3166-1 alpha-3 code.
// Generated by tools/build-meta.mjs from the world-countries dataset (ODbL) — do not edit by hand.
// num = ISO 3166-1 numeric code, used to match shapes in vendor/countries-50m.json.
export default {
${body}
};
`);
console.log(`wrote ${Object.keys(meta).length} countries, ${Object.values(meta).filter(m => m.un).length} UN members`);
